### ISSUE TITLE
Support for nodejs12.x runtime

### ISSUE THREAD

**Issue by dcvz** [refunc/lambda-runtimes#1]
Hi @antmanler,

As refunc aims to provide all AWS runtimes -- I was wondering if support could be added for `nodejs12.x`:
https://aws.amazon.com/blogs/compute/node-js-12-x-runtime-now-available-in-aws-lambda/

**Comment by Arvintian** [comment]
Refunc embrace the aws lambda ecosystem, you can just use the [lambci/docker-lambda](https://github.com/lambci/docker-lambda)'s image to run nodejs12.x. This repo also really base on [lambci/docker-lambda](https://github.com/lambci/docker-lambda).

**Comment by Arvintian** [comment]
nodejs12.x runtime already support by https://github.com/refunc/lambda-runtimes/pull/3.
